### ISSUE TITLE
Server mode

### ISSUE THREAD

**Issue by Methatronc** [mikeberger/borg_calendar#132]
Hello,
I tried putting the h2 db on a samba shared folder so that other users could edit it, but when I start another client an error message shows up saying that the db is being read, which is true, and that I have to terminate other connections ( which I don't want )  or start borg in server mode, a feature I couldn't find.
Unless it's referring to ICS server, which is nice but the client would then only read and won't be able to write, am I wrong ? I was able to import from server url to the client but any modification would need to be exported and wouldn't be synced unless I misunderstood something..
Thanks for your help !
And sorry for the dumb question if it is so, I tried looking for answered similar issues but couldn't find any.

**Comment by mikeberger** [comment]
Borg is single user. The database cannot be shared and opened by 2 clients at the same time. In fact, I would expect that eventually samba will fail to prevent a second client from connecting, resulting in a corrupted database. Shared files are useful when a single person runs Borg from multiple machines and is careful not to open 2 Borgs and the same time.

Borg had a multi-user server mode that was removed in 2008. It never worked robustly and didn't make sense once online web-based calendars proliferated. Borg can also connect to a database that is running in server mode as a separate process, rather than in file mode. Even in this case, connecting with more than 1 Borg client at a time = bad.

The only 2-way sync that Borg supports is to a caldav server. In this case, only 1 Borg database can be synced to a particular caldav calendar, or else Borg will get confused. The caldav sync is a way to get Borg connected to other web clients or android clients for a single user. It is not a multi-user feature.

**Comment by Methatronc** [comment]
Ok then I think I'll lock the db folder so that borg won't start if someone uses it, this way we'll be able to use it with multiple users as long as we don't do it at the same time.
Thanks for your answer, have a good day :)
