### ISSUE TITLE
The popup reminder pop up timing is is not accurate

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [mikeberger/borg_calendar#169]
here is a snapshot,
I am not sure when it pops up,tried to find the timing.but unable to find when and why.
The setting is set to pop up at :0 min before the appointment
![a](https://user-images.githubusercontent.com/75789716/186697639-ae0f4a08-ec8f-41b4-a311-c8f5199bb5ae.png)

**Comment by mikeberger** [comment]
There is a simple bug preventing the Due time from updating if you don't select the latest popup time for a particular appt.

While investigating this, I also found that non-todo appointments are not properly cleaned up from the reminder list - a very hard bug to track down.

The code is very difficult to follow, partly because I left in the option for the older "post-it note" style reminders, which work differently but share lots of common code that maybe they shouldn't have.
