### ISSUE TITLE
Phone numbers in Address Book tab allows alphabets in them.

### ISSUE THREAD

**Issue by gaglanicse03019** [mikeberger/borg_calendar#46]
## Description:
BORG Calendar's address book allows user to add alphabets in Cell Phone, Home Phone and Work Phone while adding a new contact.

## Steps to reproduce:
1. Start BORG Calendar 1.8.1
2. Open the "Address Book" tab.
3. Click on "Add new" button and create a dummy contact with any of the phone numbers containing alphabets in them. Note that the contact is successfully saved upon clicking "Save" button.

## Suggested Fix:
Prompt a user with an error dialog box for inserting alphabets in phone numbers.

## Environment:
**Primary test environment:**
BORG - Berger-Organizer 1.8.1
Build Time: 2015-01-17 14:51:28
Java 1.8.0_31
Windows 7 x86-64
Dell Optiplex 745 (Intel Core 2 Duo E6300)

**Secondary test environment:**
BORG - Berger-Organizer 1.8.1
Build Time: 2015-01-17 14:51:28
Java 1.7.0_65
Ubuntu 14.04 LTS x86-64
Macbook Pro 13" (Intel Core i5-2415M)

## Metadata:
**Severity:** Low
**Reproducible:** Yes (always)
**Affected platforms:** All

**Comment by mikeberger** [comment]
Some people prefer to use letters in phone numbers. that's why phones have letters on the buttons as well as numbers. So, this is not a bug.

In any case, no phone number validation of any type will be done. Phone validation was attempted multiple times by college students and caused many problems. Adding a feature to validate global phone number formats is not easy.
