### ISSUE TITLE
JNI Error Occured

### ISSUE THREAD

**Issue by Skipper07** [mikeberger/borg_calendar#87]
I am getting a JNI error after installing in Borg Calendar. It would possible an exception thrown.

**Comment by mikeberger** [comment]
What version of BORG did you install?
What is your OS?
What is the exception text?

**Comment by Skipper07** [comment]
I have installed the latest version.

On windows 10  planning to test it in Linux and OSX as well.

I'll send you the screenshot of the problem soon.

I'm planning to use it for my software testing unit and prefer to use an executable jar to run.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Skipper07** [comment]
As promised.

Here are the screenshots (please see attachments)
[cid:image001.png@01D61AFA.A9A2E720]

And

[cid:image002.png@01D61AFA.CD3F4430]

Thanks,
Najam

**Comment by mikeberger** [comment]
the screenshots do not show on github

**Comment by Skipper07** [comment]
Ahh I can send to your private email if possible...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mikeberger** [comment]
you can send emails to mike@mbcsoft.com

**Comment by mikeberger** [comment]
The screenshots don't provide the full error, but if you are using the latest version and have java8 installed, then it is because the borg.exe wrapper is getting confused by the presence of java 8. The latest BORG was compiled with Java 10 and will give a JNI error if somehow the java 8 jre is invoked to run BORG. 

To run with the java 10 jre that is provided, open a CMD window in the BORG program folder: c:\Program Files\BORGCalendar and type:
jre\bin\java -jar borg.jar

You can also create a run.bat file with this command in the BORG folder.

I use the third-party tool launch4j to create the borg.exe wrapper. Perhaps I configured something wrong? I will see if I can get it to ignore java 8. I will have to find an old machine to test this on as I will not install java 8 on my main machine.

If I can fix it, I will release a new version with Java 13.

**Comment by mikeberger** [comment]
I just released a new version. I hope it does a better job at forcing the use of the JRE that comes in the download. If it can't find the included jre, it should refuse to run.
I have not yet tested this with the public java 8 jre installed.
