### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [mikeberger/borg_calendar#92]
Thanks for the program under a free open source license! Added a program to a Russian-language site about free open source software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BE%D1%84%D0%B8%D1%81/%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B/borg-%D0%BA%D0%B0%D0%BB%D0%B5%D0%BD%D0%B4%D0%B0%D1%80%D1%8C-%D1%81-%D0%BE%D1%82%D1%81%D0%BB%D0%B5%D0%B6%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87.html).

Please do not abandon the project! This is a very interesting program!

Will stable versions be published here?

**Comment by mikeberger** [comment]
Hi. I don't really have new features planned for the program, but I will keep it working if it is broken by OS changes.

The average user, who doesn't understand Java, will probably be happy staying on release 1.8.3 forever, which uses Java 8.

The 1.9 releases are stable, but I mark them as "Pre-release" because I worry about current users running into problems related to the new Java releases and how Oracle has made a mess out of Java for desktop applications. So, the BORG 1.9 code is very stable. It is Java that is a concern. I did not want existing users to feel the need to upgrade to 1.9 and then have problems.

**Comment by mrkaban** [comment]
Thank you, I see!
